### ISSUE TITLE
Where is the train.py

### ISSUE THREAD

**Issue by YangyangQu** [aasharma90/NighttimeDepthandFlow#1]
Thank you for publishing your code.I can not find the train.py

**Comment by aasharma90** [comment]
Hi @nameCody 

Thanks for your interest. I've deliberately withheld the training code, as it still requires some cleaning up. I'll release it in a while. However, if you are interested and need it urgently, please contact me at aashish.sharma@u.nus.edu, and I can share the training code snippets with you. 

Thanks!

**Comment by YangyangQu** [comment]
OK,thank you a lot
